# this workflow maintained at https://codeberg.org/r-codeberg/woodpecker-ci
# please file bug reports and feature requests to help it improve!

matrix:
  IMAGE:
    - rocker/verse

when:
  - branch: "${CI_REPO_DEFAULT_BRANCH}"
    event: push
  - event: pull_request
  - event: tag

variables:
  print_branch: &print_branch
    - echo $DA_BRANCH

  step_setup: &setup
    - name: setup
      image: ${IMAGE}
      pull: true
      commands:
        - <<: *da_branch

steps:
  - <<: *setup
